apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "mongodb://10.0.0.12:27017/catalogue"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    app: catalogue
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---

apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: "mongo"
            - name: APP_GIT_URL
              value: "https://github.com/roboshop-devops-project-v3/catalogue"
            - name: DB_HOST
              value: "10.0.0.12"
            - name: SCHEMA_FILE
              value: "db/master-data.js"
      restartPolicy: Never
  backoffLimit: 3
