
apiVersion: v1
kind: ConfigMap
metadata:
   name: frontend
data:
  CATALOGUE_URL: "http://catalogue:8080/"
  USER_URL: "http://user:8080/"
  CART_URL: "http://cart:8080/"
  SHIPPING_URL: "http://shipping:8080/"
  PAYMENT_URL: "http://payment:8080/"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend


---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer   # So you can access from browser
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
