apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: CATALOGUE_HOST
              value: "catalogue.roboshop.svc.cluster.local"
            - name: USER_HOST
              value: "user.roboshop.svc.cluster.local"
            - name: CART_HOST
              value: "cart.roboshop.svc.cluster.local"
            - name: SHIPPING_HOST
              value: "shipping.roboshop.svc.cluster.local"
            - name: PAYMENT_HOST
              value: "payment.roboshop.svc.cluster.local"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer   # So you can access from browser
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
