apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment:latest
          ports:
            - containerPort: 8080
          env:
            - name: CART_HOST
              value: "cart.roboshop"
            - name: USER_HOST
              value: "user.roboshop"
            - name: AMQP_HOST
              value: "10.0.0.10"

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
