apiVersion: v1
kind: ConfigMap
metadata:
   name: payment
data:
 "AMQP_HOST": "10.0.0.11"
 "AMQP_PASS": "roboshop"
 "AMQP_USER": "roboshop123"
 "CART_HOST": cart
 "CART_PORT": "8080"
 "USER_HOST": user
 "USER_PORT": "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payment

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
