apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping:latest
          ports:
            - containerPort: 8080
          env:
            - name: CART_ENDPOINT
              value: "http://cart.roboshop:8080"
            - name: DB_HOST
              value: "10.0.0.15"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    app: shipping
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: "mysql"
            - name: APP_GIT_URL
              value: "https://github.com/roboshop-devops-project-v3/shipping"
            - name: DB_HOST
              value: "10.0.0.15"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "RoboShop@1"
            - name: SCHEMA_FILE
              value: "db/schema.sql"
      restartPolicy: Never
  backoffLimit: 3

---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-master-data
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: "mysql"
            - name: APP_GIT_URL
              value: "https://github.com/roboshop-devops-project-v3/shipping"
            - name: DB_HOST
              value: "10.0.0.15"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "RoboShop@1"
            - name: SCHEMA_FILE
              value: "db/master-data.sql"
      restartPolicy: Never
  backoffLimit: 3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-triggers
spec:
  template:
    spec:
      containers:
        - name: schema-load
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: DB_TYPE
              value: "mysql"
            - name: APP_GIT_URL
              value: "https://github.com/roboshop-devops-project-v3/shipping"
            - name: DB_HOST
              value: "10.0.0.15"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "RoboShop@1"
            - name: SCHEMA_FILE
              value: "db/triggers.sql"
      restartPolicy: Never
  backoffLimit: 3

