apiVersion: v1
kind: ConfigMap
metadata:
 name: user
data:
 "MONGO": "true"
 "MONGO_URL": "mongodb://10.0.0.16:27017/users"
 "REDIS_URL": "redis://10.0.0.10:6379"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
