apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
stringData:
  MYSQL_USER: "root"         # change if you use a different user
  MYSQL_PASSWORD: "roboshop" # change to your real password
