apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: roboshop
type: Opaque
stringData:
  AMQP_USER: "guest"     # better to create a dedicated user, see notes below
  AMQP_PASS: "guest"
