apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: { app: shipping }
spec:
  replicas: 1
  selector: { matchLabels: { app: shipping } }
  template:
    metadata:
      labels: { app: shipping }
    spec:
      containers:
        - name: shipping
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
          ports: [{ containerPort: 8080 }]
          envFrom:
            - configMapRef: { name: shipping }
          env:
            - name: MYSQL_USER
              valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_USER } }
            - name: MYSQL_PASSWORD
              valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_PASSWORD } }
